// <auto-generated />
namespace Newspaper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdDate_to_officer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdDate_to_officer));
        
        string IMigrationMetadata.Id
        {
            get { return "202003180754255_createdDate_to_officer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
