// <auto-generated />
namespace Newspaper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class officer_complement_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(officer_complement_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202003180606558_officer_complement_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
